import os
import stat

class LauncherGenerator:
    def __init__(self, app_name, executable_path, compat_path, proton_path):
        """
        Initializes the LauncherGenerator.
        app_name: Name of the application (used for script filename).
        executable_path: Full path to the UWP .exe file.
        compat_path: Full path to the proton compatdata directory.
        proton_path: Full path to the Proton installation directory.
        """
        self.app_name = app_name
        self.executable_path = executable_path
        self.compat_path = compat_path
        self.proton_path = proton_path
        # Directory where scripts are saved
        self.launcher_dir = os.path.expanduser('~/.local/share/uwp_runner/launchers')

    def generate_script(self):
        """
        Generates a bash script to launch the app using Proton.
        Returns the path to the generated script.
        """
        if not os.path.exists(self.launcher_dir):
            os.makedirs(self.launcher_dir)

        # Sanitize app name for filename
        safe_name = "".join(c for c in self.app_name if c.isalnum() or c in (' ', '.', '_', '-')).strip().replace(" ", "_")
        script_path = os.path.join(self.launcher_dir, f"{safe_name}.sh")

        proton_exec = os.path.join(self.proton_path, 'proton')

        # We need to be careful with paths in bash scripts.
        # Proton usually expects STEAM_COMPAT_DATA_PATH to be set.

        script_content = f"""#!/bin/bash
# UWP Launcher for {self.app_name}
# Generated by UWP Runner

# Ensure the compatibility data path is set correctly
export STEAM_COMPAT_DATA_PATH="{self.compat_path}"
export WINEPREFIX="{self.compat_path}/pfx"

# Basic environment setup for Proton
# Some UWP apps might need specific DLL overrides or settings here.

echo "Launching {self.app_name} with Proton at {self.proton_path}..."
echo "Executable: {self.executable_path}"

# Launch using Proton's run command
"{proton_exec}" run "{self.executable_path}" "$@"
"""
        with open(script_path, 'w') as f:
            f.write(script_content)

        # Make the script executable
        st = os.stat(script_path)
        os.chmod(script_path, st.st_mode | stat.S_IEXEC)

        return script_path
